### ISSUE TITLE
Add arn-role to service accounts

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#3683]
LHDI has recommended we try adding a fully qualified role ARN to our service accounts. This should allow our pods to assume the proper IAM roles and access our RDS instance. This ticket is for getting the ARN and adding it to our service account.

```
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: <role-arn>
  name: dev-tools-service-account
  namespace: va-abd-rrd-dev
```
